import type { Metadata } from "next";
import LegalPage, { type LegalSection } from "@/components/LegalPage";

export const metadata: Metadata = { title: "Terms of Use | Zoomli", description: "Terms governing use of the Zoomli vehicle marketplace and reservation service." };

const sections: LegalSection[] = [
  { title: "1. Agreement", paragraphs: ["These terms govern access to Zoomli's website, accounts, vehicle listings and reservation-request features. By using the service, you agree to these terms and our Privacy Policy. If you do not agree, do not use the service."] },
  { title: "2. What Zoomli provides", paragraphs: ["Zoomli helps users discover vehicles, submit reservation requests and allows vehicle owners to submit listings. A website confirmation records a reservation in Zoomli; it is not evidence that payment, licence checks, a security deposit, insurance, vehicle condition or other handover requirements have been completed."], items: ["Any final vehicle-hire arrangement may include separate terms supplied before handover.", "Zoomli does not currently process online payments or offer an insurance or protection product through this website.", "Availability, rates and vehicle details may change before a separate hire arrangement is finalised."] },
  { title: "3. Eligibility and accounts", items: ["Provide accurate, current information and protect your password.", "Use the service only if you can enter a legally binding arrangement in Australia.", "A driver must satisfy the licence, age, identity and eligibility requirements communicated for the selected vehicle before handover.", "Tell us promptly if you suspect unauthorised account use."] },
  { title: "4. Reservations and cancellations", paragraphs: ["Displayed prices are estimates based on the selected dates and the information currently available. Taxes, deposits, optional products and provider-specific charges are not included unless expressly shown. Cancellation through the dashboard records the request in Zoomli; any financial or vehicle-provider consequences are governed by the separately confirmed booking terms." ] },
  { title: "5. Vehicle listings", items: ["Owners must have authority to list the vehicle and provide accurate, non-misleading information.", "Vehicles must be registered, roadworthy, safely maintained and legally available for the proposed use.", "Owners remain responsible for required licences, insurance, taxes, inspections, disclosures and handover arrangements.", "Zoomli may remove or suspend listings that are unsafe, misleading, unlawful or inconsistent with these terms."] },
  { title: "6. Acceptable use", items: ["Do not use the service unlawfully, fraudulently, to impersonate another person or to interfere with security.", "Do not scrape, reverse engineer, overload, probe or introduce malicious code into the service.", "Do not upload content you do not have the right to use or content that is deceptive, harmful or unlawful."] },
  { title: "7. Consumer rights and liability", paragraphs: ["Nothing in these terms excludes rights or consumer guarantees that cannot lawfully be excluded under the Australian Consumer Law. To the extent permitted by law, Zoomli is not responsible for indirect or consequential loss, external websites, or acts and omissions of independent vehicle owners or renters. Any limitation applies only to the extent legally permitted."] },
  { title: "8. Suspension, changes and governing law", paragraphs: ["We may restrict access to protect users, investigate misuse or comply with law. We may update the service and these terms prospectively by publishing a revised version. These terms are governed by the laws of Victoria, Australia, and disputes are subject to the courts with jurisdiction there, subject to any mandatory consumer rights."] },
];

export default function TermsPage() {
  return <LegalPage eyebrow="Using Zoomli" title="Terms of Use" summary="The ground rules for accounts, reservations, vehicle listings and responsible use of the Zoomli marketplace." updated="17 August 2026" sections={sections} />;
}
